apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sre-ai-agent
  name: sre-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-ai-agent
  template:
    metadata:
      labels:
        app: sre-ai-agent
    spec:
      serviceAccountName: sre-ai-agent
      containers:
      - name: main
        image: ghcr.io/tonygilkerson/sre-ai-agent:latest@sha256:854ff5ce58a7f5f791644c7d72542cdde1f02f6c42672ff9864a3b2dc928f51a
        command:
        - /bin/bash
        - -c
        - | 
          while true; do 
            date; echo 'ZZZzzz..'; sleep 1m; 
          done
        env:
        - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
          value: "unix:///run/dagger/engine.sock"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: dagger-llm
              key: GEMINI_API_KEY
        - name: GEMINI_MODEL
          valueFrom:
            secretKeyRef:
              name: dagger-llm
              key: GEMINI_MODEL
        volumeMounts:
        - name: dagger-engine-socket
          mountPath: /run/dagger
      volumes:
        - name: dagger-engine-socket
          hostPath:
            path: /run/dagger-dagger
            type: ""
