apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sre-ai-agent
  name: sre-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-ai-agent
  template:
    metadata:
      labels:
        app: sre-ai-agent
    spec:
      serviceAccountName: sre-ai-agent
      containers:
      - name: main
        image: ghcr.io/tonygilkerson/sre-ai-agent:latest@sha256:37877a96e1e97d7c54a0e5c17b18947d20d3e1943605852435796390ec27e5ef
        command:
        - /bin/bash
        - -c
        - | 
          while true; do 
            date; echo 'ZZZzzz..'; sleep 1m; 
          done
        env:
        - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
          value: "unix:///run/dagger/engine.sock"
        volumeMounts:
        - name: dagger-engine-socket
          mountPath: /run/dagger
      volumes:
        - name: dagger-engine-socket
          hostPath:
            path: /run/dagger-dagger
            type: ""
