apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-ai-agent-readonly
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-ai-agent-readonly
subjects:
  - kind: ServiceAccount
    name: sre-ai-agent
 
roleRef:
  kind: Role
  name: sre-ai-agent-readonly
  apiGroup: rbac.authorization.k8s.io